version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql
    networks: [app-net]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pexample"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: mydb
    depends_on:
      db:
        condition: service_healthy
    networks: [app-net]
    restart: unless-stopped

volumes:
  db-data:
    external: true

networks:
  app-net:
    external: true
